### ISSUE TITLE
How to read from array of low cardinality column?

### ISSUE THREAD

**Issue by kant777** [go-faster/ch#25]
### Discussed in https://github.com/go-faster/ch/discussions/22

<div type='discussions-op-text'>

<sup>Originally posted by **kant777** January 25, 2022</sup>
How to read from array of low cardinality string column?

Below is the parts of the code I used to Read LowCardinality Column
```
tagsKey = proto.ColStr{}
tagsKeyLC = proto.ColLowCardinality{
	Index: &tagsKey,
}
tagsKeyArr = proto.ColArr{
	Data: &tagsKeyLC,
}

Result: proto.Results{
	{Name: "tags.key", Data: &tagsKeyArr},
},
```

I get the following error

```
panic: decode block: decode block: target: tags.key: decode data: got version 30, expected 1

```
any example?
</div>

**Comment by ernado** [comment]
I will add more examples on weekend.

Also go1.18 will bring generics that will greatly improve ergonomics of such columns, that's why current implementation is kinda poor.
